[package]
name = "bank"
version = "0.1.0"
edition = "2024"

[dependencies]
spawned-rt = { workspace = true }
spawned-concurrency = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "bank"
path = "src/main.rs"