[package]
name = "name_server_with_error"
version = "0.1.0"
edition = "2021"

[dependencies]
spawned-rt = { workspace = true }
spawned-concurrency = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "name_server_with_error"
path = "src/main.rs"
