[package]
name = "spawned-concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
spawned-rt = { workspace = true }
tracing = { workspace = true }
futures = "0.3.1"

[lib]
path = "./src/lib.rs"